
version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: $MONGO_DB
    ports:
      - $MONGO_PORT:$MONGO_PORT
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:$MONGO_PORT/
  
  redis:
    image: redis
    restart: on-failure
    command: redis-server --loglevel warning --requirepass $REDIS_PASSWORD
    ports:
      - $REDIS_PORT:$REDIS_PORT

  web:
    build: .
    command: sh -c "npm run migration:run:dev && npm run start:dev"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - $PORT:$PORT
    depends_on:
      - mongo
      - redis
    environment:
      PORT: $PORT
      MONGO_HOST: mongo
      MONGO_PORT: $MONGO_PORT
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DB: $MONGO_DB
      AWESOME_API_URL: $AWESOME_API_URL
      REDIS_USER: $REDIS_USER
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_HOST: redis
      REDIS_PORT: $REDIS_PORT
      REDIS_DB: $REDIS_DB
      REDIS_TTL: $REDIS_TTL
